<a href="https://colab.research.google.com/github/VIKGO123/Outlier-Detection-and-Class-Segmentation/blob/master/OutlierDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')  #Mounting google drive

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  #importing libraries

In [0]:
Gloves = pd.read_excel("gdrive/My Drive/ml_hack/IndiaMart/Phase 1 Dataset Hackathon (1)d09fdc4.xlsx", sheet_name=0)#reading excel file sheet0

In [0]:
Kurta = pd.read_excel("gdrive/My Drive/ml_hack/IndiaMart/Phase 1 Dataset Hackathon (1)d09fdc4.xlsx", sheet_name=1)#reading excel file sheet1

In [0]:
Drill = pd.read_excel("gdrive/My Drive/ml_hack/IndiaMart/Phase 1 Dataset Hackathon (1)d09fdc4.xlsx", sheet_name=2)#reading excel file sheet2

In [0]:
Drill

In [0]:
gloves_data=Gloves.as_matrix()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [0]:
drill_data=Drill.as_matrix()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [0]:
units_gloves=set(gloves_data[:,1])
units_gloves

{'Pack',
 'Pair',
 'Pair(s)',
 'Piece',
 'Pieces',
 'Set',
 'Unit',
 'Unit/Onwards',
 'pack',
 'unit'}

In [0]:
units_drill=set(drill_data[:,1])
units_drill

{'1nos',
 'Kit',
 'Number',
 'ONWARDS',
 'Pack',
 'Pc_Onwards',
 'Piece',
 'Piece(s)',
 'Set',
 'Unit',
 'Unit(s)',
 'kit',
 'pack',
 'unit'}

In [0]:
class_gloves1=['Pack','Set','pack']
class_gloves2=['Pair','Piece','Pieces','Pair(s)','Unit','Unit/Onwards','unit']#manually separting classes

In [0]:
class_drill1=['Pack','pack','Set','Kit','kit']
class_drill2=['1nos','Number','ONWARDS','Pc_Onwards','Piece','Piece(s)','Unit','Unit(s)','unit']

In [0]:
price_gloves2=[]



In [0]:
price_gloves1=[]

In [0]:
price_drill1=[]
price_drill2=[]

In [0]:
for i in class_gloves2:
    price_gloves2.append(list(Gloves[Gloves['Unit']==i]['Price']))
    
    
  

  
  

In [0]:
for i in class_drill2:
    price_drill2.append(list(Drill[Drill['Unit']==i]['Price']))
    
    
  

  
  

In [0]:
for j in class_gloves1:
    price_gloves1.append(list(Gloves[Gloves['Unit']==j]['Price']))

In [0]:
for j in class_drill1:
    price_drill1.append(list(Drill[Drill['Unit']==j]['Price']))

In [0]:
from functools import reduce
from operator import add
price_gloves1=reduce(add ,price_gloves1)

In [0]:

from functools import reduce
from operator import add
price_drill1=reduce(add ,price_drill1)

In [0]:
from functools import reduce
from operator import add
price_drill2=reduce(add ,price_drill2)

In [0]:
from functools import reduce
from operator import add
price_gloves2=reduce(add ,price_gloves2)

In [0]:
price_gloves1=np.array(price_gloves1)

In [0]:
price_gloves2=np.array(price_gloves2)

In [0]:
price_drill1=np.array(price_drill1)

In [0]:
price_drill2=np.array(price_drill2)

In [0]:
price_gloves1=price_gloves1.reshape(-1,1)
len(price_gloves1)

9

In [0]:
price_gloves2=price_gloves2.reshape(-1,1)
len(price_gloves2)

135

In [0]:
price_drill1=price_drill1.reshape(-1,1)
len(price_drill1)

59

In [0]:
price_drill2=price_drill2.reshape(-1,1)
len(price_drill2)

188

In [0]:
#Isolation forest outlier detection
from sklearn.ensemble import IsolationForest
import pandas as pd

clf = IsolationForest(max_samples=100, random_state=42)

clf.fit(price_gloves1)
output_table_gloves1 =(clf.predict(price_gloves1))
#Predicting outliers using isolation forest

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:237: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:247: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:274: UserWarning: max_samples (100) is greater than the total number of samples (9). max_samples will be set to n_samples for estimation.
  % (self.max_samples, n_samples))
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:415: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)


In [0]:
from sklearn.ensemble import IsolationForest
import pandas as pd

clf = IsolationForest(max_samples=100, random_state=42)

clf.fit(price_gloves2)
output_table_gloves2 =(clf.predict(price_gloves2))
#Predicting outliers using isolation forest

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:237: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:247: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:415: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)


In [0]:
#Isolation forest outlier detection
from sklearn.ensemble import IsolationForest
import pandas as pd

clf = IsolationForest(max_samples=100, random_state=42)

clf.fit(price_drill1)
output_table_drill1 =(clf.predict(price_drill1))
#Predicting outliers using isolation forest

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:237: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:247: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:274: UserWarning: max_samples (100) is greater than the total number of samples (59). max_samples will be set to n_samples for estimation.
  % (self.max_samples, n_samples))
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:415: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)


In [0]:
#Isolation forest outlier detection
from sklearn.ensemble import IsolationForest
import pandas as pd

clf = IsolationForest(max_samples=100, random_state=42)

clf.fit(price_drill2)
output_table_drill2 =(clf.predict(price_drill2))
#Predicting outliers using isolation forest

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:237: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:247: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/iforest.py:415: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)


In [0]:
output_table_gloves1
#output_table having -1 entries are outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1, -1])

In [0]:
output_table_gloves2

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1,
       -1,  1, -1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [0]:
output_table_drill1

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,
       -1, -1, -1, -1, -1,  1,  1,  1])

In [0]:
result_gloves1=[]

In [0]:
result_drill1=[]
result_drill2=[]

**Removing Outliers**

In [0]:
c=0
for i in output_table_gloves1:
  if(i!=-1):
    result_gloves1.append(price_gloves1[c,0])
  c=c+1    
    

In [0]:
result_gloves2=[]

In [0]:
c=0
for i in output_table_gloves2:
  if(i!=-1):
    result_gloves2.append(price_gloves2[c,0])
  c=c+1  

In [0]:
c=0
for i in output_table_drill1:
  if(i!=-1):
    result_drill1.append(price_drill1[c,0])
  c=c+1    
    

In [0]:
c=0
for i in output_table_drill2:
  if(i!=-1):
    result_drill2.append(price_drill2[c,0])
  c=c+1    
    

In [0]:
result_gloves2

**Getting Max and Min from outliers removed result to get the range for specific classes**

In [0]:
min(result_gloves2)

10

In [0]:
max(result_gloves2)

250

**['Pair','Piece','Pieces','Pair(s)','Unit','Unit/Onwards','pack','unit'] ranges from [10,250]**

In [0]:
min(result_gloves1)

51

In [0]:
max(result_gloves1)

2210

**[pack,set,Pack] ranges from [51,2210]**

In [0]:
min(result_drill1)

1069

In [0]:
max(result_drill1)

24400

**['Pack','pack','Set','Kit','kit'] ranges from [1069,24400]**

In [0]:
min(result_drill2)

675

In [0]:
max(result_drill2)

12360

**['1nos','Number','ONWARDS','Pc_Onwards','Piece','Piece(s)','Unit','Unit(s)','unit'] ranges from [675,12360]**